---
- name: Install Apache
  apt:
    name: apache2
    state: present # Ensure apache2 is installed

- name: Start Apache service
  service:
    name: apache2
    state: started # Make sure the service is running
    enabled: yes # Enable the service to start on boot
