---
# - name: Install Apache in web servers
#   hosts: web
#   become: yes # Run tasks with sudo/root privilege
#   roles:
#    # - cloudkode # Include the cloudkode role to execute its tasks
#     - KvSanojKV.apache_webserver

# - name: Create IAM Group and User
#   hosts: localhost
#   connection: local
#   gather_facts: no
#   tasks:
#     - name: Create IAM group
#       amazon.aws.iam_group:
#         name: "CloudKode"
#         state: present

# - name: Install Apache in web servers
#   hosts: web
#   become: yes # Run tasks with sudo/root privilege
#   vars_files:
#     - vars.yml # Load variables from an external file
#   tasks:
#     - name: Install apache
#       ansible.builtin.apt:
#         name: " {{ pkg }} "
#         state: present

#     - name: start apache on debian
#       ansible.builtin.service:
#         name: apache2
#         state: stopped
#       when: ansible_os_family == "Debian" # Only execute this task on Debian-based systems

- name: Create IAM Group and User
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - aws_credentials.yml
  tasks:
    - name: Create IAM group
      amazon.aws.iam_group:
        name: "CloudKode"
        state: present
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
